name: Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Get node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $NODE_VERSION
        id: nvm
      - name: Install correct node version
        uses: actions/setup-node@v2
        with:
          node-version: $NODE_VERSION
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run docz:build
