name: Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install nvm
        run: nvm install
      - name: Set the correct Node version
        run: nvm use
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run docz:build
