name: Unit test and lint

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit tests and lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run test
