name: Versioning

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit tests and lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm        
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i
    - name: Create Release Pull Request
      uses: changesets/action@v1
      with:
        # this expects you to have a npm script called version that runs some logic and then calls `changeset version`.
        version: pnpm publish:versions
