name: Versioning

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit tests and lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: Set up github user
      run: |
        git config --global user.name "@inavac182"
        git config --global user.email "16787893+inavac182@users.noreply.github.com"
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm        
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i
    - name: Version packages
      run: pnpm publish:versions
